import("xim.base.utils")

local IndexStore = {}
IndexStore.__index = IndexStore

local index_file = path.join(os.scriptdir(), "xim-index-db.lua")

function new(repodir)
    local instance = {}
    debug.setmetatable(instance, IndexStore)
    instance.repodir = repodir or "pkgindex"
    instance:init()
    return instance
end

function IndexStore:init()
    if os.isfile(index_file) then
        try {
            function()
                self._index_data = _load_index_data()
            end,
            catch {
                function(e)
                    print(e)
                    self._index_data = _build_index_data(self.repodir)
                end
            }
        }
    else
        self._index_data = _build_index_data(self.repodir)
    end
end

function IndexStore:rebuild()
    print("rebuild index database")
    self._index_data = _build_index_data(self.repodir)
end

function IndexStore:save_to_local()
    if self._need_update then
        self._need_update = false
        _save_index_data(self._index_data)
    end
end

-- getter/setter

function IndexStore:get_index_data()
    -- create deep copy of index data
    return utils.deep_copy(self._index_data)
end

function IndexStore:update_index_data(name, status)
    status = status or {}
    if status.installed then
        if self._index_data[name].installed ~= status.installed then
            self._index_data[name].installed = status.installed
            self._need_update = true
        end
    end
end

----------------------------------------

function _load_index_data()
    local index = {}
    if os.isfile(index_file) then
        index = import(
            path.basename(index_file),
            {rootdir = path.directory(index_file)}
        ).get_index_db()
    end
    return index
end

function _build_index_data(repodir)
    local index = {}
    local files = os.files(path.join(repodir, "**.lua"))
    for _, file in ipairs(files) do
        local name = path.basename(file)
        local triple = string.split(name, "_") -- name_version_maintainer
        if triple[2] then
            name = triple[1] .. "@" .. string.gsub(triple[2], "-", ".")
        end
        print(name)
        if triple[3] then
            name = name .. "@" .. triple[3]
        end
        print(name)
        index[name] = {
            installed = false,
            path = file
        }
    end
    _save_index_data(index)
    return index
end

--[[ TODO: index structure - only support string key
{
    ["name1"] = { path = "name1 package file path", installed = true },
    ["name2"] = { path = "name2 package file path", installed = false}
}
]]

function _save_index_data(index)
    print("[xlings:xim]: update index database")

    local header = string.format([[
--  Generated by xim-index-manager
--  Repo: https://github.com/d2learn/xlings
--  Time: %s
--  DO NOT MODIFY THIS FILE MANUALLY!

]], os.date("%Y-%m-%d %H:%M:%S"))

    local data = string.format("xim_index_db = %s", _serialize(index))
    index_interface = [[


function get_index_db()
    return xim_index_db
end

    ]]
    data = header .. data .. index_interface
    io.writefile(index_file, data)
end

function _serialize(obj, layer)
    layer = layer or 1
    local indent = string.rep("    ", layer)
    local s = ""
    if type(obj) == "table" then
        s = "{"
        for k, v in pairs(obj) do
            s = s .. string.format("\n%s[%s] = %s,",
                indent,
                _serialize(k),
                _serialize(v, layer + 1)
            )
        end
        s = s .. "\n" .. string.rep("    ", layer - 1) .. "}"
    elseif type(obj) == "string" then
        s = string.format("%q", obj)
    elseif type(obj) == boolean then
        s = tostring(obj)
    else
        s = tostring(obj)
    end
    return s
end

function main()
    local index_store = new(os.scriptdir())
    local index = {}
    index = index_store.index
    index["IndexStore"] = "你好"
    print(index)
    print(index_store.index)
    index_store:init()
    print(index)
    print(index_store.index)
end