bindir: xxx

xvm add target version --path xxx
xvm add target version --command xxx
xvm add target version --env name=value
xvm remove target version

xvm use target version
xvm current target
xvm run target version --args xxx
xvm list target

xvm workspace target
xvm workspace target --enable
xvm workspace target --disable