target("pylings-demo")
    set_kind("phony")
    add_files("exercises/pylings.py")
    add_files("tests/pylings-demo.py")
    on_run(function (target)
        os.exec("python3 " .. os.scriptdir() .. "/tests/pylings-demo.py")
    end)